// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roster.Infrastructure.Persistence;

#nullable disable

namespace Roster.Infrastructure.Migrations
{
    [DbContext(typeof(RosterDbContext))]
    [Migration("20260604193321_AddEmployeeDetailsAndHistory")]
    partial class AddEmployeeDetailsAndHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("roster")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Roster.Domain.Entities.Departamento", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("departamento", "roster");
                });

            modelBuilder.Entity("Roster.Domain.Entities.Empleado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<short?>("DepartamentoId")
                        .HasColumnType("smallint");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("Facturable")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("JefeInmediato")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<short?>("PaisId")
                        .HasColumnType("smallint");

                    b.Property<string>("Puesto")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("SalarioActual")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Telefono1")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("PaisId");

                    b.ToTable("empleado", "roster");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoBono", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly>("OtorgadoEn")
                        .HasColumnType("date");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("empleado_bono", "roster");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoEvaluacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EscalaMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(5m);

                    b.Property<DateOnly?>("EvaluadoEn")
                        .HasColumnType("date");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(3,1)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("empleado_evaluacion", "roster");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoHistorialPuesto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("empleado_historial_puesto", "roster");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoHistorialSalario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("Motivo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("empleado_historial_salario", "roster");
                });

            modelBuilder.Entity("Roster.Domain.Entities.Pais", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("pais", "roster");
                });

            modelBuilder.Entity("Roster.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("Roster.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Roster.Domain.Entities.Pais", "Pais")
                        .WithMany("Empleados")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoBono", b =>
                {
                    b.HasOne("Roster.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Bonos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoEvaluacion", b =>
                {
                    b.HasOne("Roster.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoHistorialPuesto", b =>
                {
                    b.HasOne("Roster.Domain.Entities.Empleado", "Empleado")
                        .WithMany("HistorialPuestos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Roster.Domain.Entities.EmpleadoHistorialSalario", b =>
                {
                    b.HasOne("Roster.Domain.Entities.Empleado", "Empleado")
                        .WithMany("HistorialSalarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Roster.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Roster.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Bonos");

                    b.Navigation("Evaluaciones");

                    b.Navigation("HistorialPuestos");

                    b.Navigation("HistorialSalarios");
                });

            modelBuilder.Entity("Roster.Domain.Entities.Pais", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
